# =========================
# Variables 
# =========================
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun 
$browser = helium-browser


# =========================
# Environment 
# =========================
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland


# =========================
# Keybindings
# =========================

# Kill active window
bind = $mainMod, Q, killactive,

# Toggle floating window
bind = $mainMod SHIFT, SPACE, togglefloating,

# Open terminal
bind = $mainMod, RETURN, exec, $terminal

# Open file manager
bind = $mainMod, E, exec, $fileManager

# Open menu
bind = $mainMod, D, exec, $menu

# Open browser
bind = $mainMod, B, exec, $browser

# Open clipboard history
bind = $mainMod, V, exec, cliphist list | rofi -dmenu | cliphist

# Fullscreen 
bind = $mainMod, F, fullscreen, 1

# Move focus
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Move windows
bind = $mainMod SHIFT, H, movewindow, l
bind = $mainMod SHIFT, L, movewindow, r
bind = $mainMod SHIFT, K, movewindow, u
bind = $mainMod SHIFT, J, movewindow, d

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move active window to workspace
bind = $mainMod SHIFT, 1, workspace, 1
bind = $mainMod SHIFT, 2, workspace, 2
bind = $mainMod SHIFT, 3, workspace, 3
bind = $mainMod SHIFT, 4, workspace, 4
bind = $mainMod SHIFT, 5, workspace, 5


# =========================
# Startup applications 
# =========================

# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# Notifications 
exec-once = mako

# Clipboard 
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# Status bar
exec-once = waybar

# Wallpaper
exec-once = swaybg -i ~/Downloads/wallpaper.jpg -m fill

# Bluetooth
exec-once = blueman-applet

# Network
exec-once = nm-applet --indicator


# =========================
# Visuals
# =========================

general {
  gaps_in = 0
  gaps_out = 0
  border_size = 1
  col.active_border = rgb(4c7899)
  col.inactive_border = rgb(333333)
}

decoration {
  rounding = 0
}

animations {
  enabled = false
}

cursor {
  no_warps = true
}

